language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sricompind/my-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sricompind/my-docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "my-docker-react"
  env: "Mydockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-850403507250"
  bucket_path: "my-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY